project:
  type: website
  output-dir: docs/

website:
  title: "my-quarto-gitpage"
  favicon: "favicon.png"
  navbar:
    right:
      - href: index.qmd
        icon: house
        text: Home
      - about.qmd
      - text: "Cheat-Sheets"
        menu:
          - text: "Quarto-CLI"
            href: menus/cheat-sheets/quarto-cli.qmd
          - text: "python"
            href: menus/cheat-sheets/python.qmd
          - text: "unix"
            href: menus/cheat-sheets/unix.qmd
          - text: "HTML"
            href: menus/cheat-sheets/html.qmd


format:
  html:
    theme: 
      light: lightcosmo
      dark: darkly 
    css: styles.css
    toc: true



