project:
  type: website
  output-dir: docs/

website:
  title: "my-quarto-gitpage"
  favicon: "favicon.png"
  navbar:
    right:
      - href: index.qmd
        icon: house
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



